# Generated by Django 5.2.3 on 2025-07-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echofy', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsession',
            old_name='mode',
            new_name='level',
        ),
    ]
