# Generated by Django 5.2.3 on 2025-07-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echofy', '0003_rename_mode_testsession_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsession',
            old_name='level',
            new_name='mode',
        ),
    ]
